### ISSUE TITLE
OE offset

### ISSUE THREAD

**Issue by 0x3333** [thomasfla/pico-pio-uart-dma-rs485#2]
I'm working a project like yours, but with 6 channels, using Pico2 + an ESP32 with Ethernet. Pico2 will do the heavy lifting of communicating with all modules and ESP32 will do the communication.

I read in the code that `OE` need to be `+1` of `TX`, do you know if this can be `-1`, like TX 9, OE 8.

Thanks!

<img width="932" alt="image" src="https://github.com/user-attachments/assets/45883f3d-fbaa-4aa0-8a57-9abd0f3248a6">

<img width="906" alt="image" src="https://github.com/user-attachments/assets/f0498391-9036-4eca-908b-bdb42e4a326c">

<img width="883" alt="image" src="https://github.com/user-attachments/assets/96b560d5-f6e0-4f35-a488-755150484da0">

**Comment by thomasfla** [comment]
Hi, 

Nice board, 

It should be doable if you change https://github.com/thomasfla/pico-pio-uart-dma-rs485/blob/83979de29e7367074544b1cbcd73a30981da400e/rs485_lib.c#L28 to have the sideset pins begin at OE (the lowest of the two) and change all the sidesets order in rs485.pio. For example 

`    set y, 7       side 0b10 [3]` -> `    set y, 7       side 0b01 [3]`
